### ISSUE TITLE
Just a quick FYI in relation to the deploy with Azure button

### ISSUE THREAD

**Issue by CouncilWise** [cocallaw/azure-tailscale-aci-deploy#5]
First off, thanks so much for putting this together!
I ended up using this a fair bit to test out Tailscale in general.

One this that I will say though is that I **think** that you can add comments to an Azure deployment thing, and if that is the case a little explanation of each thing would be pretty helpful.
I ended up getting it sorted and did the following screenshot as notes for myself.
So just some tooltip/comments or what have you about what someone should pop into each field would be a big help for newbies that's for sure.

![image](https://user-images.githubusercontent.com/66452895/195210931-a3248b6f-407c-44d0-bcee-b0dfa6474278.png)

Anyway, take it or leave it.
And thanks again for creating this in the first place

**Comment by cocallaw** [comment]
Thanks for the feedback @CouncilWise! I have been looking at a few ways to add comments and/or breakup the parameters into sections that makes it easier to understand and deploy. 

Hoping to have an update in the next week, will let you know so you can review before merging into main branch.

**Comment by cocallaw** [comment]
@CouncilWise I have updated and added metadata descriptions to all the parameters, I am still looking into options for formatting. Please review using this link and let me know if this helps - https://portal.azure.com/#create/Microsoft.Template/uri/https%3A%2F%2Fraw.githubusercontent.com%2Fcocallaw%2Fazure-tailscale-aci-deploy%2FDeployment_Updates%2FARM%2Fazuredeploy.json 

<img width="278" alt="image" src="https://user-images.githubusercontent.com/11371083/199592617-a1723d38-bb2d-4782-9c12-6273125cd2c6.png">
